# Generated by Django 4.0.3 on 2022-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('tanggal_lahir', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=10)),
            ],
        ),
    ]
